name: india_delivery_robot_app
description: Flutter app for Indian Delivery Robot operator interface with Hindi/local language support

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI and Navigation
  cupertino_icons: ^1.0.2
  material_design_icons_flutter: ^7.0.7296
  
  # State Management
  provider: ^6.0.5
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  
  # Networking
  http: ^1.1.0
  dio: ^5.3.2
  socket_io_client: ^2.0.3+1
  
  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  
  # Maps and Location
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  
  # Camera and Media
  camera: ^0.10.5+5
  image_picker: ^1.0.4
  
  # Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  
  # Utilities
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  connectivity_plus: ^5.0.1
  
  # Charts and Analytics
  fl_chart: ^0.65.0
  
  # Notifications
  flutter_local_notifications: ^16.1.0
  
  # QR Code
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
  
  # Fonts
  fonts:
    - family: Hind
      fonts:
        - asset: assets/fonts/Hind-Regular.ttf
        - asset: assets/fonts/Hind-Medium.ttf
          weight: 500
        - asset: assets/fonts/Hind-Bold.ttf
          weight: 700
    - family: NotoSansDevanagari
      fonts:
        - asset: assets/fonts/NotoSansDevanagari-Regular.ttf
        - asset: assets/fonts/NotoSansDevanagari-Bold.ttf
          weight: 700
