# Common costmap parameters for Indian urban environments
obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[-0.4, -0.25], [-0.4, 0.25], [0.4, 0.25], [0.4, -0.25]]
inflation_radius: 0.55

# Indian-specific obstacle detection
observation_sources: scan
scan: {sensor_frame: lidar_link, data_type: LaserScan, topic: scan, marking: true, clearing: true}

# Enhanced obstacle detection for crowded environments
obstacle_layer:
  enabled: true
  obstacle_range: 2.5
  raytrace_range: 3.0
  inflation_radius: 0.55
  # Higher inflation for safety in crowded Indian streets
  cost_scaling_factor: 10.0
  # Penalty for getting too close to obstacles
  lethal_cost_threshold: 100

# Social navigation parameters
social_navigation:
  enabled: true
  # Slower speeds in crowded areas
  max_vel_x: 0.5
  min_vel_x: 0.1
  # More conservative turning
  max_vel_theta: 0.5
  min_vel_theta: 0.1
  # Longer stopping distances
  acc_lim_x: 0.3
  acc_lim_theta: 0.5

# Dynamic obstacle handling
dynamic_obstacle_layer:
  enabled: true
  # Track moving objects (pedestrians, animals, vehicles)
  track_unknown_space: true
  # Update frequency for dynamic obstacles
  update_frequency: 5.0
