# Global costmap parameters for Indian urban environments
global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 1.0
  publish_frequency: 0.5
  static_map: true
  width: 100.0
  height: 100.0
  resolution: 0.05
  
  # Indian-specific parameters
  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
    - {name: social_layer, type: "costmap_2d::SocialLayer"}
  
  # Static map layer (buildings, roads, sidewalks)
  static_layer:
    enabled: true
    map_topic: /map
  
  # Dynamic obstacles
  obstacle_layer:
    enabled: true
    obstacle_range: 2.5
    raytrace_range: 3.0
    inflation_radius: 0.55
    cost_scaling_factor: 10.0
    lethal_cost_threshold: 100
  
  # Social navigation
  social_layer:
    enabled: true
    personal_space_radius: 1.0
    yield_to_pedestrians: true
    pedestrian_speed_factor: 0.5
  
  # Safety inflation
  inflation_layer:
    enabled: true
    inflation_radius: 0.55
    cost_scaling_factor: 10.0
    lethal_cost_threshold: 100
