# Local costmap parameters optimized for Indian urban environments
local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.05
  
  # Indian-specific parameters
  plugins:
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
    - {name: social_layer, type: "costmap_2d::SocialLayer"}
  
  # Enhanced obstacle detection for crowded streets
  obstacle_layer:
    enabled: true
    obstacle_range: 2.5
    raytrace_range: 3.0
    inflation_radius: 0.55
    cost_scaling_factor: 10.0
    lethal_cost_threshold: 100
  
  # Social navigation for human interaction
  social_layer:
    enabled: true
    # Respect personal space in crowded areas
    personal_space_radius: 1.0
    # Yield to pedestrians
    yield_to_pedestrians: true
    # Slower speeds near people
    pedestrian_speed_factor: 0.5
  
  # Inflation for safety margins
  inflation_layer:
    enabled: true
    inflation_radius: 0.55
    cost_scaling_factor: 10.0
    lethal_cost_threshold: 100
